apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "holborn-wordpress.appFullname" . }}
  labels:
    {{- include "holborn-wordpress.appLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "holborn-wordpress.appSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "holborn-wordpress.appSelectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "holborn-wordpress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: healthCheck
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.appRepo }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              curl -LO /health/check https://raw.githubusercontent.com/renatomefi/php-fpm-healthcheck/master/php-fpm-healthcheck \
              && chmod +x /health/check
          volumeMounts:
          - mountPath:  /health
            name:       scratch
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.appRepo }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: phpfpm
              containerPort: {{ .Values.service.appPort }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - '/health/check'
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - '/health/check'
          resources:
            {{- toYaml .Values.wordpress.resources | nindent 12 }}
          volumeMounts:
          - mountPath:  /health
            name:       scratch
      volumes:
        - name: scratch
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
