apiVersion: v1
kind: Service
metadata:
  name: {{ include "holborn-wordpress.appFullname" . }}
  labels:
    {{- include "holborn-wordpress.appLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.appPort }}
      targetPort: phpfpm
      protocol: TCP
      name: phpfpm
  selector:
    {{- include "holborn-wordpress.appSelectorLabels" . | nindent 4 }}
