apiVersion: v1
kind: Service
metadata:
  name: {{ include "holborn-wordpress.webFullname" . }}
  labels:
    {{- include "holborn-wordpress.webLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "holborn-wordpress.webSelectorLabels" . | nindent 4 }}
